### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by FuroYT** [enmity-mod/tweak#11]
I installed the latest ipa file and the app is not booting up it installed but I can’t launch the app
![Error Message](https://user-images.githubusercontent.com/90060358/194898583-f0cc916c-1d14-4b86-9cb5-350e04c63ff1.png)

**Comment by debouncedgit** [comment]
If you sideload via Sideloadly, toggle the option "**Try to support iOS 7+**".
If you didn't sideload via Sideloadly, sideload via Sideloadly. 
👍🏻

**Comment by ContentLTD** [comment]
> If you sideload via Sideloadly, toggle the option "**Try to support iOS 7+**".
> 
> If you didn't sideload via Sideloadly, sideload via Sideloadly. 
> 
> 👍🏻 
I get the same error, I cannot download Enmity any other way besides using installonair.com
To configure the Ipa file

**Comment by viviannq** [comment]
> I get the same error, I cannot download Enmity any other way besides using installonair.com

Is it possible for you to use Altstore? It’s very good and all you need is a computer with macOS or Windows 10/11.

**Comment by ContentLTD** [comment]
Reply to https://github.com/enmity-mod/tweak/issues/11#issuecomment-1296517606 : No
