### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by ExoTicZs** [enmity-mod/tweak#28]
Always takes over a minute or two to connect i usualy have to disconnect and reconnect my wifi connection pls fix :)

**Comment by SunnybeeXD** [comment]
same

**Comment by JackPlaysGames0510** [comment]
If you add this plugin https://raw.githubusercontent.com/m4fn3/AddonManager/master/dist/AddonManager.js  and then tap on plugin the type in “FixConnecting” this problem will be fixed

**Comment by ExoTicZs** [comment]
> If you add this plugin https://raw.githubusercontent.com/m4fn3/AddonManager/master/dist/AddonManager.js  and then tap on plugin the type in “FixConnecting” this problem will be fixed

Thankyou

**Comment by ljcool2006** [comment]
> If you add this plugin https://raw.githubusercontent.com/m4fn3/AddonManager/master/dist/AddonManager.js  and then tap on plugin the type in “FixConnecting” this problem will be fixed

This still occurs randomly while using Discord, even with the plugin enabled
