### ISSUE TITLE
The enmity options do not show for me on settings

### ISSUE THREAD

**Issue by sallyFoster** [enmity-mod/tweak#31]
![image](https://github.com/enmity-mod/tweak/assets/104597302/86fb2ce9-0e00-4501-995e-4e676c58fcf0)
![image](https://github.com/enmity-mod/tweak/assets/104597302/3c7dd817-f29c-4b1b-96f4-16f4b954b39a)

**Comment by colin273** [comment]
Is this still an issue on the latest version of Enmity?

**Comment by sallyFoster** [comment]
It is not

**Comment by colin273** [comment]
All right, I'll close this then. Thanks!
