### ISSUE TITLE
Enmity icon not loading on You tab

### ISSUE THREAD

**Issue by Meteony** [enmity-mod/tweak#41]
![F1C41D1F-4BE7-44D4-AE7A-92C2E0A4A581](https://github.com/enmity-mod/tweak/assets/141850520/b3b0ce17-bb13-4a1d-a1c5-a329a12f3bed)
Yup. Ain’t no serious issue but would be good to see the icon showing back up. 
Operating system: IOS 14.8 w/ taurine jailbreak
Discord client version: Newest client by Mar. 12

**Comment by marioparaschiv** [comment]
Fixed in more recent versions of Enmity.
