### ISSUE TITLE
push notifications not working?

### ISSUE THREAD

**Issue by xsmashx88x** [enmity-mod/tweak#42]
anyone else having this issue?

**Comment by Cagecellag** [comment]
> anyone else having this issue?

push notifications work fine for me

**Comment by xsmashx88x** [comment]
> > anyone else having this issue?
> 
> push notifications work fine for me

What did you use to load the ipa? Cause I’m not getting them I do with normal discord installed,

turns out using alt store or sideloadly you won’t have to be jailbroken, have a paid cert or using a paid signing service

**Comment by Cagecellag** [comment]
> > > anyone else having this issue?
> > 
> > 
> > push notifications work fine for me
> 
> What did you use to load the ipa? Cause I’m not getting them I do with normal discord installed,
> 
> turns out using alt store or sideloadly you won’t have to be jailbroken, have a paid cert or using a paid signing service

i used flekst0re with a paid certification

**Comment by xsmashx88x** [comment]
> > > > anyone else having this issue?
> > > 
> > > 
> > > push notifications work fine for me
> > 
> > 
> > What did you use to load the ipa? Cause I’m not getting them I do with normal discord installed,
> > turns out using alt store or sideloadly you won’t have to be jailbroken, have a paid cert or using a paid signing service
> 
> i used flekst0re with a paid certification

ya not paying to get notifications

**Comment by Cagecellag** [comment]
> > > > > anyone else having this issue?
> > > > 
> > > > 
> > > > push notifications work fine for me
> > > 
> > > 
> > > What did you use to load the ipa? Cause I’m not getting them I do with normal discord installed,
> > > turns out using alt store or sideloadly you won’t have to be jailbroken, have a paid cert or using a paid signing service
> > 
> > 
> > i used flekst0re with a paid certification
> 
> ya not paying to get notifications

thats fair, but ig scarlet would work if it wasn't revoked

**Comment by marioparaschiv** [comment]
This is an apple limitation. You need a paid developer certificate (100$/y) to be able to sign an IPA with notifications. We cannot do anything about this.
