### ISSUE TITLE
Couldn't work on LiveContainer

### ISSUE THREAD

**Issue by KH0000001** [enmity-mod/tweak#51]
v2.2.6

1. Install v2.2.6 Enmity. 
2. The app installed by LiveContainer.
3. Finish to install, launch the app. 
4. Display is darkout.

**Comment by KH0000001** [comment]
I could launch v2.2.5. It is a note.

**Comment by AushevAhmad** [comment]
I don't think Enmity is compatible with Live Container into he first place

**Comment by claration** [comment]
Use the install methods provided by us, using tools like these don't always have a guarentee of working with enmity or any other app for the matter.

**Comment by KH0000001** [comment]
Thank you for supports. Injail devices can’t use Enmity without SideStore or LiveContainer. I hope this app works perfectly on LiveContainer in the future:)

**Comment by Impure2411** [comment]
v2.2.6 works with LiveContainer

Also, check this issue out
https://github.com/khanhduytran0/LiveContainer/issues/290
