### ISSUE TITLE
calling bug on v2.2.6

### ISSUE THREAD

**Issue by Lilyp3892** [enmity-mod/tweak#52]
hi! I just updated to 2.2.6 from 2.2.5 and even after completely uninstalling and reinstalling 2.2.6 with no plugins or themes users are unable to hear me at all and I cannot hear them. This is not an issue on 2.2.5. Uninstalling 2.2.6 and reinstalling 2.2.5 fixed this error so I'm confident this is an error relating to 2.2.6. I should also definitely mention that this issue only started to occur when I updated to ios 18.0.1 on my 14 pro from ios 16.1.2. So 2.2.6 did work for a day or two until I updated my ios version today because I am switching to a 16. Sorry if that was confusing so both 2.2.6 and 2.2.5 had worked on my phone on ios 16.1.2 but now on ios 18.0.1 only 2.2.5 works and not 2.2.6. I should also mention before the ios update I was using trollstore as my install method and now on ios 18.0.1 that is no longer an option so I am using Signulous (with a custom icon and notifications enabled). everything other than the calling seems to work fine is there anything I can do to fix this?

**Comment by SerStars** [comment]
It's a known bug since Discord version 247, you can downgrade to 246 if you would like to

**Comment by Lilyp3892** [comment]
> It's a known bug since Discord version 247, you can downgrade to 246 if you would like to

Awesome! I'm not super sure how to do that but I'm sure Ill try to figure it out and ill let you know if it works!

**Comment by SerStars** [comment]
> I'm not super sure how to do that but I'm sure Ill try to figure it out

You can find it here: https://github.com/allorionmusic/enmity/releases/tag/v246

**Comment by Lilyp3892** [comment]
thank u so so so so much it works perfectly!!!!
