### ISSUE TITLE
Date glitch

### ISSUE THREAD

**Issue by JackPlaysGames0510** [enmity-mod/tweak#7]
The dates are in Hindi

**Comment by marioparaschiv** [comment]
Are you on bleeding-edge?

**Comment by sanderDijkxhoorn** [comment]
I’ve noticed this too, using the latest normal tweak version + Discord v125.0

**Comment by sanderDijkxhoorn** [comment]
Installing the bleeding edge version fixes this btw so just wait for a new update to support 125.0

**Comment by JackPlaysGames0510** [comment]
@localip no I’m not it’s a glitch in the latest version
